export const EASY_PASSWORD = 'EASY_PASSWORD';
export const MEDIUM_PASSWORD = 'MEDIUM_PASSWORD';
export const STRONG_PASSWORD = 'STRONG_PASSWORD';
export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';
export const RESET = 'RESET';
